library(shiny)
shinyUI(pageWithSidebar(
  headerPanel("Predicting Impact of Traffic Violation"),
  sidebarPanel(
    p("Fill the below details"),
    selectInput("gender", 
                label = h4("Select Gender of Driver:"), 
                list("M" = "M", "F" = "F")),
    selectInput("race", 
                label = h4("Select Race of Driver:"), 
                list("Asian" = "ASIAN", "Black" = "BLACK", "Hispanic" = "HISPANIC", "White" = "WHITE", "Native American" = "NATIVE AMERICAN", "Other" = "OTHER")),
    selectInput("vehicle_type", 
                label = h4("Select Type of Vehicle:"), 
                list("Automobile" = "Automobile", "Motorcycle" = "Motorcycle", "Station Wagon" = "Station Wagon", "Other" = "OTHER")),
    selectInput("color", 
                label = h4("Select Color of Vehicle:"), 
                list("Red" = "RED", "Yellow" = "YELLOW", "Black" = "BLACK", "Brown" = "BROWN", "Gold" = "GOLD", "Gray" = "GRAY")),
    selectInput("manufacturer", 
                label = h4("Select Manufacturer of Vehicle:"), 
                list("BMW" = "BMW", "Accura" = "ACCURA", "Benz" = "BENZ", "Audi" = "AUDI", "Dodge" = "DODGE", "Ford" = "FORD")),
    radioButtons("commercial_license", label = h4("Driver with Commercial License:"),
                 choices = list("Yes" = "Yes", "No" = "No")),
    selectInput("state_license", 
                label = h4("Select State issuing Driving License:"), 
                list("MD" = "MD", "NY" = "NY", "NJ" = "NJ", "MA" = "MA", "AK" = "AK", "AL" = "AL"))),
  mainPanel(
    h4("Probability of getting involved in an Accident:"),
    h4(textOutput('prob1')),
    p("85.87593874"),
    br(),
    h4("Probability of getting involved in Personal Injury:"),
    h4(textOutput('prob2')),
    p("92.5794965"),
    br(),
    h4("Probability of getting involved in Property Damage:"),
    h4(textOutput('prob3')),
    p("48.25425223"),
    br(),
    h4("Probability of getting involved in Fatality:"),
    h4(textOutput('prob4')),
    p("76.45428729"),
    br(),
    h4("Probability of getting involved in Alcohol Consumption:"),
    h4(textOutput('prob5')),
    p("84.32467629"),
    br(),
    h4("Probability of violations in Work Zone:"),
    h4(textOutput('prob6')),
    p("69.422444475")
    )))
    
